import type { Metadata } from "next";

import "./globals.css";

import {Inter} from 'next/font/google'

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};
const inter = Inter({ subsets: ["latin"], variable: "--font-inter"  });
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
  className={`${inter.variable} antialiased bg-[linear-gradient(145deg,_#000000,_#1b1b1b,_#3d3d3d,_#101010)] bg-[length:200%_200%] animate-[neonGlow_5s_ease-in-out_infinite]`}
  style={{ color: 'white' }}
>
        {children}
      </body>
    </html>
  );
}
